name: Validate Markdown

on:
  # Trigger the workflow on pull request
  pull_request_target:
    branches: 
      - main
    paths:
      - '**.md'
      - '**.ipynb'

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-broken-paths:
    name: Check Broken Relative Paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check broken Paths
        id: check-broken-paths
        uses: john0isaac/action-check-markdown@v0.0.4-alpha
        with:
          command: check-broken-paths
          directory: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Leave paths tracking comment
        if: ${{ steps.check-broken-paths.outputs.is-valid == 1 }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              We have automatically detected missing tracking id from the following relative paths in your lessons.
              Please check the file paths and associated paths inside them.
              Learn more from our [contributing guide](https://github.com/microsoft/generative-ai-for-beginners/blob/main/CONTRIBUTING.md).
              # Check Missing Tracking from Paths
              ${{ env.PATHS_TRACKING }}
              `
            })
      - name: Update workflow run status
        if: ${{ steps.check-broken-paths.outputs.is-valid == 1 }}
        run: exit 1
            
